# dockerfile.dev
FROM python:3.12-bullseye

# 必要なパッケージのインストール
RUN apt-get update && apt-get install -y \
    git \
    less \
    tree \
    curl \
    jq \
    zsh \
    && rm -rf /var/lib/apt/lists/*

# タイムゾーンの設定
RUN ln -snf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && echo 'Asia/Tokyo' > /etc/timezone

# Oh My Zshのインストール
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended

# Gitのコマンド補完を有効にする
RUN echo "autoload -Uz compinit && compinit" >> /root/.zshrc

# Zshをデフォルトシェルに設定
RUN chsh -s /bin/zsh root

# requirements.txtからのインストール
COPY requirements.txt /home/requirements.txt
RUN pip install --no-cache-dir -r /home/requirements.txt
